// <auto-generated />
using System;
using ManageDocument.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageDocument.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250526161127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ManageDocument.Entities.Document", b =>
                {
                    b.Property<int>("DocumentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("DocumentNumber");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ManageDocument.Entities.DocumentDetail", b =>
                {
                    b.Property<int>("AccountCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DocumentNumber")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AccountCode");

                    b.HasIndex("DocumentNumber");

                    b.ToTable("DocumentDetails");
                });

            modelBuilder.Entity("ManageDocument.Entities.DocumentDetail", b =>
                {
                    b.HasOne("ManageDocument.Entities.Document", "Document")
                        .WithMany("DocumentDetails")
                        .HasForeignKey("DocumentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManageDocument.Entities.Document", b =>
                {
                    b.Navigation("DocumentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
